/**
 * certificates.ts
 * Auto-generated from the uploaded certificates archive.
 */

export interface CertificateEntry {
  id: string;
  title: string;
  issuer: string;
  category: string;
  date: string | null;
  verifyLink: string | null;
  pdfUrl: string;
  summary: string;
}

export const certificates: CertificateEntry[] = [
  {
    id: "cad-infosys-certificate",
    title: "CAD Infosys Certificate",
    issuer: "CAD Infosys",
    category: "CAD & Design",
    date: "January 29, 2025",
    verifyLink: "https://validate.onwingspan.com/",
    pdfUrl: "/certificates/CAD%20Infosys%20Certificate.pdf",
    summary: "CAD Infosys Certificate completed through CAD Infosys.",
  },
  {
    id: "astronomy-exploring-time-and-space",
    title: "Astronomy- Exploring Time and Space",
    issuer: "Coursera",
    category: "Aerospace & Science",
    date: null,
    verifyLink: "https://coursera.org/verify/28GMGXBK84NK",
    pdfUrl: "/certificates/Coursera/Astronomy-%20Exploring%20Time%20and%20Space.pdf",
    summary: "Astronomy- Exploring Time and Space completed through Coursera.",
  },
  {
    id: "astrotech-the-science-and-technology-behind-astronomical-discovery",
    title: "AstroTech The Science and Technology behind Astronomical Discovery",
    issuer: "Coursera",
    category: "Aerospace & Science",
    date: null,
    verifyLink: "https://coursera.org/verify/7N4KPU3LCJLG",
    pdfUrl: "/certificates/Coursera/AstroTech%20The%20Science%20and%20Technology%20behind%20Astronomical%20Discovery.pdf",
    summary: "AstroTech The Science and Technology behind Astronomical Discovery completed through Coursera.",
  },
  {
    id: "innovation-through-design",
    title: "Innovation through design",
    issuer: "Coursera",
    category: "Aerospace & Science",
    date: null,
    verifyLink: "https://coursera.org/verify/G9HG6E6RWXYD",
    pdfUrl: "/certificates/Coursera/Innovation%20through%20design.pdf",
    summary: "Innovation through design completed through Coursera.",
  },
  {
    id: "introduction-to-mechanical-engineering-design-and-manufacturing-with-fusion360",
    title: "Introduction to Mechanical Engineering Design And Manufacturing with Fusion360",
    issuer: "Coursera",
    category: "Aerospace & Science",
    date: null,
    verifyLink: "https://coursera.org/verify/YRHR9ZFQCPBD",
    pdfUrl: "/certificates/Coursera/Introduction%20to%20Mechanical%20Engineering%20Design%20And%20Manufacturing%20with%20Fusion360.pdf",
    summary: "Introduction to Mechanical Engineering Design And Manufacturing with Fusion360 completed through Coursera.",
  },
  {
    id: "mailchimp",
    title: "Mailchimp",
    issuer: "Coursera",
    category: "Aerospace & Science",
    date: null,
    verifyLink: "https://coursera.org/verify/EFZJR78DZSDC",
    pdfUrl: "/certificates/Coursera/Mailchimp.pdf",
    summary: "Mailchimp completed through Coursera.",
  },
  {
    id: "sustainable-development",
    title: "Sustainable Development",
    issuer: "Coursera",
    category: "Aerospace & Science",
    date: null,
    verifyLink: "https://coursera.org/verify/HTFN34Q5ACYC",
    pdfUrl: "/certificates/Coursera/Sustainable%20Development.pdf",
    summary: "Sustainable Development completed through Coursera.",
  },
  {
    id: "web-application-technologies-and-django",
    title: "Web Application Technologies and Django",
    issuer: "Coursera",
    category: "Aerospace & Science",
    date: null,
    verifyLink: "https://coursera.org/verify/638SLYXNKST3",
    pdfUrl: "/certificates/Coursera/Web%20Application%20Technologies%20and%20Django.pdf",
    summary: "Web Application Technologies and Django completed through Coursera.",
  },
  {
    id: "academic-research-foundations-quantitative",
    title: "Academic Research Foundations Quantitative",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 14, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Academic%20Research%20Foundations%20Quantitative.pdf",
    summary: "Academic Research Foundations Quantitative completed through LinkedIn Learning.",
  },
  {
    id: "business-writing-principles",
    title: "Business Writing Principles",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 19, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Business%20Writing%20Principles.pdf",
    summary: "Business Writing Principles completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-academic-paper-writing-and-ipr",
    title: "Academic Paper Writing and IPR",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/CertificateOfCompletion_Academic%20Paper%20Writing%20and%20IPR.pdf",
    summary: "Academic Paper Writing and IPR completed through LinkedIn Learning.",
  },
  {
    id: "consulting-foundations",
    title: "Consulting Foundations",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Consulting%20Foundations.pdf",
    summary: "Consulting Foundations completed through LinkedIn Learning.",
  },
  {
    id: "copyright-for-creatives-protecting-your-work",
    title: "Copyright for Creatives Protecting Your Work",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Copyright%20for%20Creatives%20Protecting%20Your%20Work.pdf",
    summary: "Copyright for Creatives Protecting Your Work completed through LinkedIn Learning.",
  },
  {
    id: "creating-a-business-plan",
    title: "Creating a Business Plan",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Creating%20a%20Business%20Plan.pdf",
    summary: "Creating a Business Plan completed through LinkedIn Learning.",
  },
  {
    id: "creative-collaboration",
    title: "Creative Collaboration",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Creative%20Collaboration.pdf",
    summary: "Creative Collaboration completed through LinkedIn Learning.",
  },
  {
    id: "critical-roles-consultants-play-and-the-skills-you-need-to-fill-them",
    title: "Critical Roles Consultants Play and the Skills You Need to Fill Them",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Critical%20Roles%20Consultants%20Play%20and%20the%20Skills%20You%20Need%20to%20Fill%20Them.pdf",
    summary: "Critical Roles Consultants Play and the Skills You Need to Fill Them completed through LinkedIn Learning.",
  },
  {
    id: "getting-your-ideas-approved",
    title: "Getting Your Ideas Approved",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Getting%20Your%20Ideas%20Approved.pdf",
    summary: "Getting Your Ideas Approved completed through LinkedIn Learning.",
  },
  {
    id: "information-literacy",
    title: "Information Literacy",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 18, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Information%20Literacy.pdf",
    summary: "Information Literacy completed through LinkedIn Learning.",
  },
  {
    id: "leading-with-innovation",
    title: "Leading with Innovation",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Leading%20with%20Innovation.pdf",
    summary: "Leading with Innovation completed through LinkedIn Learning.",
  },
  {
    id: "preparing-for-successful-communication",
    title: "Preparing for Successful Communication",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 21, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Preparing%20for%20Successful%20Communication.pdf",
    summary: "Preparing for Successful Communication completed through LinkedIn Learning.",
  },
  {
    id: "spss-for-academic-research",
    title: "SPSS for Academic Research",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 16, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/SPSS%20for%20Academic%20Research.pdf",
    summary: "SPSS for Academic Research completed through LinkedIn Learning.",
  },
  {
    id: "technical-writing-quick-start-guides",
    title: "Technical Writing Quick Start Guides",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 18, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Technical%20Writing%20Quick%20Start%20Guides.pdf",
    summary: "Technical Writing Quick Start Guides completed through LinkedIn Learning.",
  },
  {
    id: "thinking-creatively",
    title: "Thinking Creatively",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Thinking%20Creatively.pdf",
    summary: "Thinking Creatively completed through LinkedIn Learning.",
  },
  {
    id: "understanding-intellectual-property",
    title: "Understanding Intellectual Property",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 22, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Understanding%20Intellectual%20Property.pdf",
    summary: "Understanding Intellectual Property completed through LinkedIn Learning.",
  },
  {
    id: "understanding-patents-a-deeper-dive",
    title: "Understanding Patents A Deeper Dive",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 22, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Understanding%20Patents%20A%20Deeper%20Dive.pdf",
    summary: "Understanding Patents A Deeper Dive completed through LinkedIn Learning.",
  },
  {
    id: "word-2016-creating-long-documents",
    title: "Word 2016 Creating Long Documents",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 18, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Word%202016%20Creating%20Long%20Documents.pdf",
    summary: "Word 2016 Creating Long Documents completed through LinkedIn Learning.",
  },
  {
    id: "writing-articles",
    title: "Writing Articles",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 17, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Writing%20Articles.pdf",
    summary: "Writing Articles completed through LinkedIn Learning.",
  },
  {
    id: "writing-white-papers",
    title: "Writing White Papers",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 14, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Academic%20Reasearch%20Paper%20and%20IPR/Writing%20White%20Papers.pdf",
    summary: "Writing White Papers completed through LinkedIn Learning.",
  },
  {
    id: "become-a-business-analytics-developing-manager",
    title: "Become a Business Analytics & Developing Manager",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Oct 18, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Become%20a%20Business%20Analytics%20%26%20Developing%20Manager/Become%20a%20Business%20Analytics%20%26%20Developing%20Manager.pdf",
    summary: "Become a Business Analytics & Developing Manager completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-become-an-entrepreneur-inside-a-company",
    title: "Become an Entrepreneur Inside a Company",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 10, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Become%20an%20Entrepreneur%20Inside%20a%20Company.pdf",
    summary: "Become an Entrepreneur Inside a Company completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-conducting-a-swot-analysis",
    title: "Conducting a SWOT Analysis",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Conducting%20a%20SWOT%20Analysis.pdf",
    summary: "Conducting a SWOT Analysis completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-creating-a-business-plan",
    title: "Creating a Business Plan",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Feb 23, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Creating%20a%20Business%20Plan.pdf",
    summary: "Creating a Business Plan completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-employee-to-entrepreneur",
    title: "Employee to Entrepreneur",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 10, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Employee%20to%20Entrepreneur.pdf",
    summary: "Employee to Entrepreneur completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-entrepreneurship-finding-and-testing-your-business-idea",
    title: "Entrepreneurship Finding and Testing Your Business Idea",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Entrepreneurship%20Finding%20and%20Testing%20Your%20Business%20Idea.pdf",
    summary: "Entrepreneurship Finding and Testing Your Business Idea completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-entrepreneurship-foundations",
    title: "Entrepreneurship Foundations",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 10, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Entrepreneurship%20Foundations.pdf",
    summary: "Entrepreneurship Foundations completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-leading-in-government",
    title: "Leading in Government",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Leading%20in%20Government.pdf",
    summary: "Leading in Government completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-project-management-government-projects",
    title: "Project Management Government Projects",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Project%20Management%20Government%20Projects.pdf",
    summary: "Project Management Government Projects completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-revenue-staffing-and-expense-models-explained",
    title: "Revenue Staffing and Expense Models Explained",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Revenue%20Staffing%20and%20Expense%20Models%20Explained.pdf",
    summary: "Revenue Staffing and Expense Models Explained completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-selling-with-authenticity",
    title: "Selling with Authenticity",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Selling%20with%20Authenticity.pdf",
    summary: "Selling with Authenticity completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-social-media-marketing-for-small-business",
    title: "Social Media Marketing for Small Business",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Social%20Media%20Marketing%20for%20Small%20Business.pdf",
    summary: "Social Media Marketing for Small Business completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-social-selling-reaching-prospects",
    title: "Social Selling Reaching Prospects",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Social%20Selling%20Reaching%20Prospects.pdf",
    summary: "Social Selling Reaching Prospects completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-unique-ways-to-generate-creative-ideas",
    title: "Unique Ways to Generate Creative Ideas",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Unique%20Ways%20to%20Generate%20Creative%20Ideas.pdf",
    summary: "Unique Ways to Generate Creative Ideas completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-use-an-entrepreneurial-mindset-to-find-success-and-fulfillment-at-work",
    title: "Use an Entrepreneurial Mindset to Find Success and Fulfillment at Work",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 10, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Use%20an%20Entrepreneurial%20Mindset%20to%20Find%20Success%20and%20Fulfillment%20at%20Work.pdf",
    summary: "Use an Entrepreneurial Mindset to Find Success and Fulfillment at Work completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-virtual-selling-for-sales-professionals",
    title: "Virtual Selling for Sales Professionals",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Nov 12, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Enterprenuership/CertificateOfCompletion_Virtual%20Selling%20for%20Sales%20Professionals.pdf",
    summary: "Virtual Selling for Sales Professionals completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-ethical-hacking-footprinting-and-reconnaissance",
    title: "Ethical Hacking Footprinting and Reconnaissance",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 24, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Hacking/CertificateOfCompletion_Ethical%20Hacking%20Footprinting%20and%20Reconnaissance.pdf",
    summary: "Ethical Hacking Footprinting and Reconnaissance completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-ethical-hacking-introduction-to-ethical-hacking",
    title: "Ethical Hacking Introduction to Ethical Hacking",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 09, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Hacking/CertificateOfCompletion_Ethical%20Hacking%20Introduction%20to%20Ethical%20Hacking.pdf",
    summary: "Ethical Hacking Introduction to Ethical Hacking completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-becoming-an-impactful-and-influential-leader",
    title: "Becoming an Impactful and Influential Leader",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Becoming%20an%20Impactful%20and%20Influential%20Leader.pdf",
    summary: "Becoming an Impactful and Influential Leader completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-building-your-team",
    title: "Building Your Team",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Building%20Your%20Team.pdf",
    summary: "Building Your Team completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-business-development-strategic-planning",
    title: "Business Development Strategic Planning",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Business%20Development%20Strategic%20Planning.pdf",
    summary: "Business Development Strategic Planning completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-business-ethics-for-managers-and-leaders",
    title: "Business Ethics for Managers and Leaders",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Business%20Ethics%20for%20Managers%20and%20Leaders.pdf",
    summary: "Business Ethics for Managers and Leaders completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-how-to-manage-your-manager",
    title: "How to Manage Your Manager",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_How%20to%20Manage%20Your%20Manager.pdf",
    summary: "How to Manage Your Manager completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-human-resources-compensation-and-benefits",
    title: "Human Resources Compensation and Benefits",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Human%20Resources%20Compensation%20and%20Benefits.pdf",
    summary: "Human Resources Compensation and Benefits completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-human-resources-foundations",
    title: "Human Resources Foundations",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Human%20Resources%20Foundations.pdf",
    summary: "Human Resources Foundations completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-human-resources-understanding-hr-systems-features-and-benefits",
    title: "Human Resources Understanding HR Systems Features and Benefits",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Human%20Resources%20Understanding%20HR%20Systems%20Features%20and%20Benefits.pdf",
    summary: "Human Resources Understanding HR Systems Features and Benefits completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-leadership-foundations-leadership-styles-and-models",
    title: "Leadership Foundations Leadership Styles and Models",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Leadership%20Foundations%20Leadership%20Styles%20and%20Models.pdf",
    summary: "Leadership Foundations Leadership Styles and Models completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-leadership-foundations",
    title: "Leadership Foundations",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Leadership%20Foundations.pdf",
    summary: "Leadership Foundations completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-leadership-skills-for-the-future",
    title: "Leadership Skills for The Future",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Leadership%20Skills%20for%20The%20Future.pdf",
    summary: "Leadership Skills for The Future completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-leading-and-motivating-people-with-different-personalities",
    title: "Leading and Motivating People with Different Personalities",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Leading%20and%20Motivating%20People%20with%20Different%20Personalities.pdf",
    summary: "Leading and Motivating People with Different Personalities completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-leading-and-working-in-teams",
    title: "Leading and Working in Teams",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Leading%20and%20Working%20in%20Teams.pdf",
    summary: "Leading and Working in Teams completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-management-foundations",
    title: "Management Foundations",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Management%20Foundations.pdf",
    summary: "Management Foundations completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-managing-a-diverse-team",
    title: "Managing a Diverse Team",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Managing%20a%20Diverse%20Team.pdf",
    summary: "Managing a Diverse Team completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-managing-your-time",
    title: "Managing Your Time",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Managing%20Your%20Time.pdf",
    summary: "Managing Your Time completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-organizational-culture",
    title: "Organizational Culture",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Organizational%20Culture.pdf",
    summary: "Organizational Culture completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-strategic-planning-case-studies",
    title: "Strategic Planning Case Studies",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Strategic%20Planning%20Case%20Studies.pdf",
    summary: "Strategic Planning Case Studies completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-strategic-planning-foundations",
    title: "Strategic Planning Foundations",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Strategic%20Planning%20Foundations.pdf",
    summary: "Strategic Planning Foundations completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-teamwork-foundations",
    title: "Teamwork Foundations",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_Teamwork%20Foundations.pdf",
    summary: "Teamwork Foundations completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-the-art-of-leadership-getabstract-summary",
    title: "The Art of Leadership getAbstract Summary",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Apr 20, 2023",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/ITML/CertificateOfCompletion_The%20Art%20of%20Leadership%20getAbstract%20Summary.pdf",
    summary: "The Art of Leadership getAbstract Summary completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-excel-essential-training-microsoft-365",
    title: "Excel Essential Training Microsoft 365",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 02, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_Excel%20Essential%20Training%20Microsoft%20365.pdf",
    summary: "Excel Essential Training Microsoft 365 completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-excel-formulas-and-functions-quick-tips-2020",
    title: "Excel Formulas and Functions Quick Tips 2020",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 01, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_Excel%20Formulas%20and%20Functions%20Quick%20Tips%202020.pdf",
    summary: "Excel Formulas and Functions Quick Tips 2020 completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-excel-introduction-to-formatting-2019",
    title: "Excel Introduction to Formatting 2019",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 01, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_Excel%20Introduction%20to%20Formatting%202019.pdf",
    summary: "Excel Introduction to Formatting 2019 completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-excel-introduction-to-formulas-and-functions",
    title: "Excel Introduction to Formulas and Functions",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 02, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_Excel%20Introduction%20to%20Formulas%20and%20Functions.pdf",
    summary: "Excel Introduction to Formulas and Functions completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-excel-pivottable-quick-tips",
    title: "Excel PivotTable Quick Tips",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 01, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_Excel%20PivotTable%20Quick%20Tips.pdf",
    summary: "Excel PivotTable Quick Tips completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-excel-pivottables-for-beginners",
    title: "Excel PivotTables for Beginners",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 01, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_Excel%20PivotTables%20for%20Beginners.pdf",
    summary: "Excel PivotTables for Beginners completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-microsoft-office-first-steps",
    title: "Microsoft Office First Steps",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 01, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_Microsoft%20Office%20First%20Steps.pdf",
    summary: "Microsoft Office First Steps completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-powerpoint-designing-better-slides",
    title: "PowerPoint Designing Better Slides",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 02, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_PowerPoint%20Designing%20Better%20Slides.pdf",
    summary: "PowerPoint Designing Better Slides completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-powerpoint-essential-training-microsoft-365",
    title: "PowerPoint Essential Training Microsoft 365",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 02, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_PowerPoint%20Essential%20Training%20Microsoft%20365.pdf",
    summary: "PowerPoint Essential Training Microsoft 365 completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-powerpoint-quick-tips",
    title: "PowerPoint Quick Tips",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 01, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_PowerPoint%20Quick%20Tips.pdf",
    summary: "PowerPoint Quick Tips completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-word-essential-training-microsoft-365",
    title: "Word Essential Training Microsoft 365",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 01, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_Word%20Essential%20Training%20Microsoft%20365.pdf",
    summary: "Word Essential Training Microsoft 365 completed through LinkedIn Learning.",
  },
  {
    id: "certificateofcompletion-word-quick-tips",
    title: "Word Quick Tips",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 01, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/CertificateOfCompletion_Word%20Quick%20Tips.pdf",
    summary: "Word Quick Tips completed through LinkedIn Learning.",
  },
  {
    id: "microsoft-office-fundamentals-word-powerpoint-and-excel",
    title: "Microsoft Office Fundamentals Word, Powerpoint and Excel",
    issuer: "LinkedIn Learning",
    category: "Professional Learning",
    date: "Mar 01, 2024",
    verifyLink: null,
    pdfUrl: "/certificates/Linkedin/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel/Microsoft%20Office%20Fundamentals_%20Word%2C%20Powerpoint%20and%20Excel.pdf",
    summary: "Microsoft Office Fundamentals Word, Powerpoint and Excel completed through LinkedIn Learning.",
  },
  {
    id: "saylor-marksheet",
    title: "Saylor Marksheet",
    issuer: "Saylor Academy",
    category: "Self-Study",
    date: null,
    verifyLink: null,
    pdfUrl: "/certificates/Saylor/Bitcoin%20for%20everybody/Saylor%20Marksheet.pdf",
    summary: "Saylor Marksheet completed through Saylor Academy.",
  },
  {
    id: "saylor",
    title: "Bitcoin for everybody",
    issuer: "Saylor Academy",
    category: "Self-Study",
    date: "April 22, 2022",
    verifyLink: null,
    pdfUrl: "/certificates/Saylor/Bitcoin%20for%20everybody/Saylor.pdf",
    summary: "Bitcoin for everybody completed through Saylor Academy.",
  },
  {
    id: "615411aa2b4eee37f836b1d0",
    title: "615411aa2b4eee37f836b1d0",
    issuer: "UNESCO",
    category: "Global Learning",
    date: null,
    verifyLink: "https://framerspace.com/verifyCertificate",
    pdfUrl: "/certificates/UNESCO/615411aa2b4eee37f836b1d0.pdf",
    summary: "615411aa2b4eee37f836b1d0 completed through UNESCO.",
  },
];